# Generated by Django 3.1.4 on 2021-06-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historywords',
            name='place',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
