# Generated by Django 3.1.4 on 2021-06-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_historywords_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='historywords',
            name='sentenceAuthor',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
